name = "TypeDBORM"
uuid = "9e96080b-bc94-4a8c-a0b7-3f708a4db810"
authors = ["Frank Urbach"]
version = "0.1.0"

[deps]
TypeDBClient = "7ffdda62-db04-4838-9798-febd00f3125c"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
